### ISSUE TITLE
Question. How do you handle changelogs with this approach?

### ISSUE THREAD

**Issue by kvernon** [wakatime/semver-action#30]
Lately we've been discussing using branch prefixes as identifiers for level of change, but one thing I'm missing in this automation of versioning is how to automate a changelog.

How would you do this with your tool? Or do you all have suggestion on an approach to take?

Thanks,
Kelly

**Comment by gandarez** [comment]
Changelog is automatically calculated only for development branch. Our releases expect a manual defined changelog.

**Comment by kvernon** [comment]
@gandarez thanks for the info, and just to summarize to make sure I get you on this...

1. if work branches, like feature/ bugfix are going into the develop branch, then semver-action will generate a changelog. 2. When this is doing a release, it expects the changelog to already be generated. 

Please let me know if I have this correct, and if I do I might have one more question :D

**Comment by alanhamlett** [comment]
Here's an example of our wakatime-cli repo, which uses this semver-action https://github.com/wakatime/wakatime-cli/blob/develop/.github/workflows/on_push.yml
